// Every player-visible string. Swap this module to translate the game.
export const STR = {
  app: { title: 'BracketBot Robotics', loading: 'Loading BracketBot…' },
  common: {
    next: 'Next', back: 'Back', run: 'Run', retry: 'Try again', hub: 'Hub', done: 'Done', close: 'Close',
    correct: 'Correct!', wrong: 'Not quite — try again.', step: 'Step {n} of 5', concept: 'Concept check',
    badgeTitle: 'Badge earned!', realRobot: 'Try it on the real BracketBot', backToHub: 'Back to hub',
    move: 'Move',
  },
  hub: {
    title: 'BracketBot Robotics',
    subtitle: 'Three small missions with one real robot. Nothing here is faked: the robot really tunes, really learns, and sometimes really fails.',
    levels: {
      pid: { name: 'Hold the Line', blurb: 'Someone keeps pushing the robot. Tune P, I and D so it holds its spot.', icon: '🎯' },
      rl: { name: 'Teach the Rally', blurb: 'Choose senses, controls and a reward, then train the robot to return a serve.', icon: '🏓' },
      vision: { name: 'Robot Eyes', blurb: 'Label photos, train a tiny brain, and test it on pictures it never saw.', icon: '👁️' },
    },
    progress: 'Step {n} of 5',
    badge: 'Badge earned',
    play: 'Play',
    resume: 'Continue',
    realRobot: 'Real robot',
    reset: 'Reset progress',
    resetConfirm: 'Tap again to erase everything',
    resetDone: 'Progress erased',
  },
  real: {
    pid: {
      title: 'Hold the Line — on the real BracketBot',
      lines: [
        'Mark a target line on a clear, level floor and put BracketBot on it.',
        'The robot needs measured forward position and wheel speed control — the same loop you tuned here.',
        'Use a repeatable, low-force disturbance (a rolling ball or a weight on a string), not your hands.',
        'Start with the wheels raised or on a test stand, check the command sign, then lower it and re-tune the gains.',
      ],
      warn: 'Always have a supervised stop button and the manufacturer\'s speed and current limits enabled.',
    },
    rl: {
      title: 'Teach the Rally — on the real BracketBot',
      lines: [
        'Fix the robot base, fence the paddle workspace, and use a repeatable ball launcher.',
        'Every sense you picked here maps to a real sensor: ball tracking camera, a contact sensor on the paddle, a landing detector on the table.',
        'Check joint directions, limits, speeds and the emergency stop before any learned policy moves the arm.',
        'A policy trained in simulation is a starting point, not a hardware-ready controller.',
      ],
      warn: 'Never stand inside the paddle workspace while a learned policy is enabled.',
    },
    vision: {
      title: 'Robot Eyes — on the real BracketBot',
      lines: [
        'Place one red, blue or yellow card in front of the head camera, centred in the frame.',
        'Collect examples under at least two kinds of lighting, and keep a separate test set the robot never trains on.',
        'Crop the same centre region you used here before measuring the colour.',
        'This activity ends at "the robot says a colour". Connecting that to motors is a separate, reviewed step.',
      ],
      warn: 'Keep fingers and cables away from the mast carriage while the head moves.',
    },
  },
  pid: {
    title: 'Hold the Line',
    skip: 'Fast-forward',
    gains: { kp: 'P — how hard it pushes back', ki: 'I — how much it remembers', kd: 'D — how much it brakes' },
    disturbances: { push: 'Quick push', long_push: 'Long push', steady_pull: 'Steady pull' },
    metrics: { max: 'Biggest error', overshoot: 'Overshoot', tail: 'Last 2 s' },
    steps: {
      1: {
        title: 'See the problem',
        lead: 'BracketBot must stay on the orange line. Right now its controller is switched off (all gains are 0). Press Run and watch what a quick push does.',
        note: 'The red band on the graph is when the push happens. The graph shows how far the robot is from the line.',
        result: 'The robot ended {cm} cm from the line and never came back. It has no idea it moved.',
      },
      2: {
        title: 'Add P',
        lead: 'P pushes the robot back toward the line, harder the further away it is. Slide P up and run the push.',
        note: 'Try a small P and a big P. Watch what happens after it gets back to the line.',
        needP: 'P is still 0 — slide it up before running.',
        result: 'It comes back! But look at the overshoot: {over} cm past the line. A big P overshoots and wobbles.',
      },
      3: {
        title: 'Add D',
        lead: 'D is the brake: it pushes against the robot\'s speed. Your best P-only overshoot was {best} cm. Add some D and beat it.',
        note: 'Too much D and the robot gets twitchy — the sensor is a little late, and a big brake on late news causes shaking.',
        needD: 'D is still 0 — slide it up before running.',
        result: 'Overshoot {over} cm — better than {best} cm. D calms the wobble.',
        worse: 'Overshoot {over} cm is not better than {best} cm. Try a different mix of P and D.',
      },
      4: {
        title: 'Add I',
        lead: 'Now someone pulls the robot gently for 7 seconds. P alone leaves it stuck a little off the line. I adds up that small error over time and fixes it.',
        note: 'Watch the I number: it grows slowly while the error stays on one side.',
        needI: 'The robot is stuck {tail} cm off the line. Add some I so it remembers the error.',
        notYet: 'Still {tail} cm off in the last 2 seconds. Try more I, or a bit more P.',
        result: 'Back on the line and staying there. That is what I is for.',
      },
      5: {
        title: 'The exam',
        lead: 'One set of gains must hold the line against all three disturbances. Run each one. Changing a gain clears the board.',
        note: 'Pass = within 5 cm of the line for the last 2 seconds.',
        partial: 'Passed that one. Now run the others with the same gains.',
        failed: 'Not stable — {tail} cm off in the last 2 seconds. Adjust and try again.',
        result: 'All three held with one set of gains. That is a tuned controller.',
        hint: 'Hint: the engineers\' gains are P {kp}, I {ki}, D {kd}. You still have to run them.',
      },
    },
    concept: {
      question: 'The robot always ends up 4 cm short of the line when someone leans on it. Which gain fixes that?',
      options: ['P — push harder', 'I — remember the small error and add it up', 'D — brake more'],
      answer: 1,
      explain: 'A steady lean needs a steady push back, and only I keeps growing while the error stays.',
    },
    badge: 'You tuned a real PID controller. The same three numbers run on the real BracketBot\'s wheels.',
  },
  rl: {
    title: 'Teach the Rally',
    presets: {
      contact: { name: 'Touch it', pick: 'Reward: touch it', blurb: 'Big points just for touching the ball. A legal return is only a small bonus.' },
      return: { name: 'Return it', pick: 'Reward: return it', blurb: 'Big points only when the ball lands on the other side. Touching alone earns almost nothing.' },
    },
    outcomes: ['Miss', 'Touch, but not over the net', 'Legal return'],
    steps: {
      1: {
        title: 'Set the task',
        lead: 'Before a robot can learn, someone has to decide what "done" looks like. Watch the three replays and pick the one where the job is done.',
        note: 'The ball is served from the far end. BracketBot only gets one swing.',
        replay: 'Replay {n}',
        options: ['Replay A is the job done', 'Replay B is the job done', 'Replay C is the job done'],
        correct: 'Yes — over the net and landing on the far half. That is a legal return, and that is the task.',
        wrong: ['The robot missed the ball completely. Not done.', 'It touched the ball, but the ball never made it over the net. Touching is not the task.', ''],
      },
      2: {
        title: 'Senses and controls',
        lead: 'A robot learns from what it can sense and what it can move. Sort the cards.',
        note: 'Drag a card into a box, or use its Move button.',
        zones: { sense: 'Robot senses (observations)', control: 'Robot controls (actions)' },
        cards: [
          { id: 'x', label: 'How far away the ball is', zone: 'sense' },
          { id: 'y', label: 'How high the ball is', zone: 'sense' },
          { id: 'vx', label: 'How fast the ball flies toward it', zone: 'sense' },
          { id: 'vy', label: 'Whether the ball is rising or falling', zone: 'sense' },
          { id: 'h', label: 'Paddle height (mast up/down)', zone: 'control' },
          { id: 't', label: 'Paddle tilt (wrist flat/high)', zone: 'control' },
        ],
        check: 'Check',
        correct: 'Right. Four senses in, two controls out — that is the whole robot as far as learning is concerned.',
        wrong: '{n} card(s) are in the wrong box. Think: is this something the robot reads, or something it moves?',
      },
      3: {
        title: 'Choose the reward',
        lead: 'The robot chases points. You decide what earns points. Compare the two reward plans, then pick one to train with.',
        note: 'You can come back and train with the other plan later.',
      },
      4: {
        title: 'Train',
        lead: 'Press Train. The robot tries 300 serves, and after each one it nudges its brain toward whatever earned more points. This is real learning — it can also fail to improve.',
        note: 'The orange trail is the last serve. Reward is the average over the last 20 serves.',
        using: 'Training with the plan: {preset}',
        train: 'Train (300 serves)',
        cancel: 'Stop',
        switchPreset: 'Switch to "{preset}" (starts fresh)',
        switched: 'Brain reset. Now training with "{preset}".',
        cancelled: 'Stopped after {n} serves. The robot keeps what it learned so far.',
        done: 'Done. Reward went from {first} (first 50) to {last} (last 50). Legal returns during training: {legal}. Now check it on serves it has never seen.',
        m: { episode: 'Serves', reward: 'Reward (last 20)', contacts: 'Touches', legal: 'Legal returns' },
      },
      5: {
        title: 'Evaluate',
        lead: 'Reward during training can lie. The real test: 20 serves the robot never trained on, before and after learning.',
        note: 'Before = the untrained robot. After = the brain you just trained.',
        before: 'Before', after: 'After',
        run: 'Run the 20-serve test',
        improved: 'Legal returns went from {b} to {a} on unseen serves. That is real improvement.',
        notImproved: 'Legal returns went from {b} to {a}. It did not improve much — that happens. Go back and train longer, or try the other reward plan.',
      },
    },
    concept: {
      question: 'Which number proves the robot actually returns balls?',
      options: ['The training reward going up', 'Legal returns on the 20 serves it never saw', 'The number of serves it trained on'],
      answer: 1,
      explain: 'Reward is whatever we chose to pay for. Returns on unseen serves are the job itself.',
    },
    badge: 'You set a task, chose senses and controls, designed a reward, trained, and evaluated. Those are the five steps of every RL project — including the real BracketBot.',
  },
  vision: {
    title: 'Robot Eyes',
    labels: { red: 'Red', blue: 'Blue', yellow: 'Yellow' },
    steps: {
      1: {
        title: 'Label the photos',
        lead: 'BracketBot\'s head camera took 18 photos of coloured balls. It has no idea what colours are. Tap a photo, then tap the colour you see.',
        note: 'Every label you give becomes one example the robot learns from. Wrong labels teach wrong things.',
        needTwo: 'The robot needs at least 2 examples of every colour before it can learn.',
      },
      2: {
        title: 'Train',
        lead: 'Press Train. The robot fits a tiny brain — 12 numbers — to your 18 labelled examples.',
        note: 'It only looks at the average colour of the middle of each photo. Nothing else.',
        train: 'Train',
        done: 'Trained on {n} examples. It gets {acc}% of them right. But that is on photos it has already seen…',
      },
      3: {
        title: 'Test on new photos',
        lead: 'Here are 12 photos the robot never saw, with different backgrounds and lighting. It got {n} of 12.',
        note: 'Green ✓ = right, red ✗ = wrong. This is the score that matters.',
        total: 'Correct',
      },
      4: {
        title: 'Improve it',
        lead: 'Six tricky photos: dim yellows, purple-ish blues, orange-ish reds. Label them, then train again with 24 examples.',
        note: 'After retraining, the robot is scored on the same 12 test photos so the comparison is fair.',
        retrain: 'Train again (24 examples)',
        done: 'Retrained. Compare the numbers: more examples of the hard cases changed what the robot believes.',
        m: { testBefore: 'Test before', testAfter: 'Test after', hardBefore: 'Tricky before', hardAfter: 'Tricky after' },
      },
      5: {
        title: 'A real object',
        lead: 'Now show the robot something real. Take or choose a photo with one red, blue or yellow thing in the middle.',
        note: 'The robot only reads the middle of the picture (the orange square). Backgrounds and shadows count too.',
        pick: 'Take / choose a photo',
        result: 'The robot says: {label} ({pct}% sure).',
        caveat: 'It has only three answers, so it will call a green apple something. That is not a bug — it is what a 3-class model is.',
        failed: 'Could not read that image. Try another one.',
      },
    },
    concept: {
      question: 'Why test the robot on photos it never trained on?',
      options: ['Because training photos are boring', 'To find out whether it learned the colour, not just those exact photos', 'Because more photos always means a better score'],
      answer: 1,
      explain: 'A model can memorise its examples. Only new examples show whether it learned the idea.',
    },
    badge: 'You collected data, trained a real classifier, tested it honestly, and improved it with harder examples. The real BracketBot\'s camera uses the same steps.',
  },
}
