// Every player-visible string. Swap this module to translate the game.
export const STR = {
  app: { title: 'BracketBot Robotics', loading: 'Loading BracketBot…' },
  common: {
    next: 'Next', back: 'Back', run: 'Run', retry: 'Try again', hub: 'Hub', done: 'Done', close: 'Close',
    correct: 'Correct!', wrong: 'Not quite — try again.', step: 'Step {n} of 5', concept: 'Concept check',
    badgeTitle: 'Badge earned!', realRobot: 'Try it on the real BracketBot', backToHub: 'Back to hub',
    move: 'Move',
  },
  hub: {
    title: 'BracketBot Robotics',
    subtitle: 'Three small missions with one real robot. Nothing here is faked: the robot really tunes, really learns, and sometimes really fails.',
    levels: {
      pid: { name: 'Hold the Line', blurb: 'Someone keeps pushing the robot. Tune P, I and D so it holds its spot.', icon: '🎯' },
      rl: { name: 'Teach the Rally', blurb: 'Choose senses, controls and a reward, then train the robot to return a serve.', icon: '🏓' },
      vision: { name: 'Robot Eyes', blurb: 'Label photos, train a tiny brain, and test it on pictures it never saw.', icon: '👁️' },
    },
    progress: 'Step {n} of 5',
    badge: 'Badge earned',
    play: 'Play',
    resume: 'Continue',
    realRobot: 'Real robot',
    reset: 'Reset progress',
    resetConfirm: 'Tap again to erase everything',
    resetDone: 'Progress erased',
  },
  real: {
    pid: {
      title: 'Hold the Line — on the real BracketBot',
      lines: [
        'Mark a target line on a clear, level floor and put BracketBot on it.',
        'The robot needs measured forward position and wheel speed control — the same loop you tuned here.',
        'Use a repeatable, low-force disturbance (a rolling ball or a weight on a string), not your hands.',
        'Start with the wheels raised or on a test stand, check the command sign, then lower it and re-tune the gains.',
      ],
      warn: 'Always have a supervised stop button and the manufacturer\'s speed and current limits enabled.',
    },
    rl: {
      title: 'Teach the Rally — on the real BracketBot',
      lines: [
        'Fix the robot base, fence the paddle workspace, and use a repeatable ball launcher.',
        'Every sense you picked here maps to a real sensor: ball tracking camera, a contact sensor on the paddle, a landing detector on the table.',
        'Check joint directions, limits, speeds and the emergency stop before any learned policy moves the arm.',
        'A policy trained in simulation is a starting point, not a hardware-ready controller.',
      ],
      warn: 'Never stand inside the paddle workspace while a learned policy is enabled.',
    },
    vision: {
      title: 'Robot Eyes — on the real BracketBot',
      lines: [
        'Place one red, blue or yellow card in front of the head camera, centred in the frame.',
        'Collect examples under at least two kinds of lighting, and keep a separate test set the robot never trains on.',
        'Crop the same centre region you used here before measuring the colour.',
        'This activity ends at "the robot says a colour". Connecting that to motors is a separate, reviewed step.',
      ],
      warn: 'Keep fingers and cables away from the mast carriage while the head moves.',
    },
  },
  pid: {
    title: 'Hold the Line',
    skip: 'Fast-forward',
    gains: { kp: 'P — how hard it pushes back', ki: 'I — how much it remembers', kd: 'D — how much it brakes' },
    disturbances: { push: 'Quick push', long_push: 'Long push', steady_pull: 'Steady pull' },
    metrics: { max: 'Biggest error', overshoot: 'Overshoot', tail: 'Last 2 s' },
    steps: {
      1: {
        title: 'See the problem',
        lead: 'BracketBot must stay on the orange line. Right now its controller is switched off (all gains are 0). Press Run and watch what a quick push does.',
        note: 'The red band on the graph is when the push happens. The graph shows how far the robot is from the line.',
        result: 'The robot ended {cm} cm from the line and never came back. It has no idea it moved.',
      },
      2: {
        title: 'Add P',
        lead: 'P pushes the robot back toward the line, harder the further away it is. Slide P up and run the push.',
        note: 'Try a small P and a big P. Watch what happens after it gets back to the line.',
        needP: 'P is still 0 — slide it up before running.',
        result: 'It comes back! But look at the overshoot: {over} cm past the line. A big P overshoots and wobbles.',
      },
      3: {
        title: 'Add D',
        lead: 'D is the brake: it pushes against the robot\'s speed. Your best P-only overshoot was {best} cm. Add some D and beat it.',
        note: 'Too much D and the robot gets twitchy — the sensor is a little late, and a big brake on late news causes shaking.',
        needD: 'D is still 0 — slide it up before running.',
        result: 'Overshoot {over} cm — better than {best} cm. D calms the wobble.',
        worse: 'Overshoot {over} cm is not better than {best} cm. Try a different mix of P and D.',
      },
      4: {
        title: 'Add I',
        lead: 'Now someone pulls the robot gently for 7 seconds. P alone leaves it stuck a little off the line. I adds up that small error over time and fixes it.',
        note: 'Watch the I number: it grows slowly while the error stays on one side.',
        needI: 'The robot is stuck {tail} cm off the line. Add some I so it remembers the error.',
        notYet: 'Still {tail} cm off in the last 2 seconds. Try more I, or a bit more P.',
        result: 'Back on the line and staying there. That is what I is for.',
      },
      5: {
        title: 'The exam',
        lead: 'One set of gains must hold the line against all three disturbances. Run each one. Changing a gain clears the board.',
        note: 'Pass = within 5 cm of the line for the last 2 seconds.',
        partial: 'Passed that one. Now run the others with the same gains.',
        failed: 'Not stable — {tail} cm off in the last 2 seconds. Adjust and try again.',
        result: 'All three held with one set of gains. That is a tuned controller.',
        hint: 'Hint: the engineers\' gains are P {kp}, I {ki}, D {kd}. You still have to run them.',
      },
    },
    concept: {
      question: 'The robot always ends up 4 cm short of the line when someone leans on it. Which gain fixes that?',
      options: ['P — push harder', 'I — remember the small error and add it up', 'D — brake more'],
      answer: 1,
      explain: 'A steady lean needs a steady push back, and only I keeps growing while the error stays.',
    },
    badge: 'You tuned a real PID controller. The same three numbers run on the real BracketBot\'s wheels.',
  },
}
