// Every player-visible string. Swap this module to translate the game.
export const STR = {
  app: { title: 'BracketBot Robotics', loading: 'Loading BracketBot…' },
  common: {
    next: 'Next', back: 'Back', run: 'Run', retry: 'Try again', hub: 'Hub', done: 'Done', close: 'Close',
    correct: 'Correct!', wrong: 'Not quite — try again.', gotIt: 'Got it', step: 'Step {n} of {total}', concept: 'Concept check',
    badgeTitle: 'Badge earned!', realRobot: 'Try it on the real BracketBot', backToHub: 'Back to hub',
    move: 'Move',
  },
  hub: {
    title: 'BracketBot Robotics',
    subtitle: 'Three small missions with one real robot. Nothing here is faked: the robot really tunes, really learns, and sometimes really fails.',
    levels: {
      pid: { name: 'Hold the Line', blurb: 'Make a two-wheeled robot stand up, stop wobbling, and hold its spot when pushed.', icon: '🎯' },
      rl: { name: 'Teach the Rally', blurb: 'Set the task, pick senses, controls and a reward, let it explore, train, and test it on serves it never saw.', icon: '🏓' },
      vision: { name: 'Robot Eyes', blurb: 'Label photos, train a tiny brain, and test it on pictures it never saw.', icon: '👁️' },
    },
    progress: 'Step {n} of {total}',
    badge: 'Badge earned',
    play: 'Play',
    resume: 'Continue',
    realRobot: 'Real robot',
    reset: 'Reset progress',
    resetConfirm: 'Tap again to erase everything',
    resetDone: 'Progress erased',
  },
  real: {
    pid: {
      title: 'Hold the Line — on the real BracketBot',
      lines: [
        'Mark a target line on a clear, level floor and put BracketBot on it.',
        'The robot needs measured forward position and wheel speed control — the same loop you tuned here.',
        'Use a repeatable, low-force disturbance (a rolling ball or a weight on a string), not your hands.',
        'Start with the wheels raised or on a test stand, check the command sign, then lower it and re-tune the gains.',
      ],
      warn: 'Always have a supervised stop button and the manufacturer\'s speed and current limits enabled.',
    },
    rl: {
      title: 'Teach the Rally — on the real BracketBot',
      lines: [
        'Fix the robot base, fence the paddle workspace, and use a repeatable ball launcher.',
        'Every sense you picked here maps to a real sensor: ball tracking camera, a contact sensor on the paddle, a landing detector on the table.',
        'Check joint directions, limits, speeds and the emergency stop before any learned policy moves the arm.',
        'A policy trained in simulation is a starting point, not a hardware-ready controller.',
      ],
      warn: 'Never stand inside the paddle workspace while a learned policy is enabled.',
    },
    vision: {
      title: 'Robot Eyes — on the real BracketBot',
      lines: [
        'Place one red, blue or yellow card in front of the head camera, centred in the frame.',
        'Collect examples under at least two kinds of lighting, and keep a separate test set the robot never trains on.',
        'Crop the same centre region you used here before measuring the colour.',
        'This activity ends at "the robot says a colour". Connecting that to motors is a separate, reviewed step.',
      ],
      warn: 'Keep fingers and cables away from the mast carriage while the head moves.',
    },
  },
  pid: {
    title: 'Hold the Line',
    skip: 'Fast-forward',
    gains: { kp: 'P — how hard it chases the lean', kd: 'D — how hard it fights the tipping speed', kh: 'Hold — how much it leans toward the line', khShort: 'Hold', ki: 'I — how long it remembers being off the line' },
    disturbances: { push: 'Quick push', long_push: 'Long push', steady_pull: 'Steady pull', none: 'No push' },
    graphs: { tilt: 'Tilt (degrees)', position: 'Distance from the line (cm)' },
    metrics: { stood: 'Stayed up?', yes: 'Yes', fellAt: 'Fell at {t} s', fell: 'Fell', wobble: 'Wobble', drift: 'Drifted', tail: 'Last 2 s' },
    steps: {
      1: {
        title: 'Watch it fall',
        lead: 'BracketBot stands on two wheels. Nothing holds it up except its own motors — and right now they are off. Press Run.',
        note: 'It starts with a tiny lean, like a real robot the moment you let go. The tilt graph shows how far it leans.',
        result: 'Gravity won in {t} seconds. To stand, the robot has to drive its wheels under itself faster than it falls.',
      },
      2: {
        title: 'Add P',
        lead: 'P drives the wheels toward the lean: the more it tips, the harder the wheels chase. Slide P up and run.',
        note: 'Watch the tilt graph. Does it stand still, or swing back and forth?',
        needP: 'P is still 0 — slide it up before running.',
        result: 'It fought for {t} s (it was {t0} s with no controller), but every swing got bigger. Chasing the lean is not enough: by the time it reacts, it is already tipping the other way.',
        stood: 'It stayed up! Look at the tilt graph — is it calm, or swinging?',
      },
      3: {
        title: 'Add D',
        lead: 'D looks at how fast the robot is tipping and pushes against that, before the lean gets big. Add some D and run — this time with a push.',
        note: 'The red band is the push. A standing robot still rolls away: watch the distance graph.',
        needD: 'D is still 0 — slide it up before running.',
        fell: 'Still fell at {t} s. Try more D, or a bit less P.',
        result: 'It stands! Wobble {wobble}°. But it drifted {drift} cm — balancing is not the same as staying put.',
      },
      4: {
        title: 'Stay on the line',
        lead: 'To come back, the robot must lean a little toward the line and roll there. Hold decides how much to lean. Slide it up and survive the push.',
        note: 'Too much Hold and it leans too far and falls. Pass = within 15 cm of the line for the last 2 seconds.',
        needH: 'Hold is still 0 — slide it up before running.',
        fell: 'It fell. Too much Hold leans it over — back off a little.',
        notYet: 'Upright, but {tail} cm off the line in the last 2 seconds. Adjust Hold (or P and D).',
        result: 'Balanced and back on the line ({tail} cm). That is a full balancing controller.',
      },
      5: {
        title: 'The exam',
        lead: 'One set of gains must stand and hold the line against all three disturbances. The steady pull is new: it leans on the robot the whole time.',
        note: 'Changing a gain clears the board. A steady pull leaves the robot stuck a little off the line — I slowly walks it back.',
        partial: 'Passed that one. Now run the others with the same gains.',
        failed: 'Not stable — {tail} cm off in the last 2 seconds. Adjust and try again.',
        needI: 'Upright, but parked {tail} cm off the line while being pulled. Add some I so it remembers the error and keeps correcting.',
        result: 'All three held with one set of gains. That is a tuned controller — the real BracketBot runs exactly this kind of loop.',
        hint: 'Hint: the engineers\' gains are P {kp}, D {kd}, Hold {kh}, I {ki}. You still have to run them.',
      },
    },
    concept: {
      question: 'Someone leans on the robot for a long time and it stands still, 20 cm from the line. Which gain fixes that?',
      options: ['P — chase the lean harder', 'I — remember the small error and keep adding it up', 'D — fight the tipping speed harder'],
      answer: 1,
      explain: 'A steady push needs a steady correction, and only I keeps growing while the error stays.',
    },
    badge: 'You made a two-wheeled robot stand, stop wobbling, hold its spot, and shrug off a steady pull. The same loop runs on the real BracketBot\'s wheels.',
  },
  rl: {
    title: 'Teach the Rally',
    presets: {
      contact: { name: 'Touch it', pick: 'Reward: touch it', blurb: 'Big points just for touching the ball. A legal return is only a small bonus.' },
      return: { name: 'Return it', pick: 'Reward: return it', blurb: 'Big points only when the ball lands on the other side. Touching alone earns almost nothing.' },
    },
    outcomes: ['Miss', 'Touch, but not over the net', 'Legal return'],
    tilts: ['flat', 'medium', 'high'],
    steps: {
      1: {
        title: 'Set the task',
        lead: 'Before a robot can learn, someone has to decide what "done" looks like. Watch the three replays and pick the one where the job is done.',
        note: 'The ball is served from the far end. BracketBot only gets one swing.',
        replay: 'Replay {n}',
        options: ['Replay A is the job done', 'Replay B is the job done', 'Replay C is the job done'],
        correct: 'Yes — over the net and landing on the far half. That is a legal return, and that is the task.',
        wrong: ['The robot missed the ball completely. Not done.', 'It touched the ball, but the ball never made it over the net. Touching is not the task.', ''],
      },
      2: {
        title: 'Senses and controls',
        lead: 'A robot learns from what it can sense and what it can move. Sort the cards.',
        note: 'Drag a card into a box, or use its Move button.',
        zones: { sense: 'Robot senses (observations)', control: 'Robot controls (actions)' },
        cards: [
          { id: 'x', label: 'How far away the ball is', zone: 'sense' },
          { id: 'y', label: 'How high the ball is', zone: 'sense' },
          { id: 'vx', label: 'How fast the ball flies toward it', zone: 'sense' },
          { id: 'vy', label: 'Whether the ball is rising or falling', zone: 'sense' },
          { id: 'h', label: 'Paddle height (mast up/down)', zone: 'control' },
          { id: 't', label: 'Paddle tilt (wrist flat/high)', zone: 'control' },
        ],
        check: 'Check',
        correct: 'Right. Four senses in, two controls out — that is the whole robot as far as learning is concerned.',
        wrong: '{n} card(s) are in the wrong box. Think: is this something the robot reads, or something it moves?',
      },
      3: {
        title: 'Choose the reward',
        lead: 'The robot chases points. You decide what earns points. Compare the two reward plans, then pick one to train with.',
        note: 'Changing the plan later starts the robot\'s brain from scratch.',
      },
      5: {
        title: 'Train',
        lead: 'Press Train. The robot tries 300 serves, and after each one it nudges its brain toward whatever earned more points. This is real learning — it can also fail to improve.',
        note: 'The orange trail is the last serve. Watch the bars: as it learns, it becomes surer about one choice.',
        using: 'Plan: {preset} · Exploring: {explore}',
        train: 'Train (300 serves)',
        cancel: 'Stop',
        switchPreset: 'Switch to "{preset}" (starts fresh)',
        switched: 'Brain reset. Now training with "{preset}".',
        cancelled: 'Stopped after {n} serves. The robot keeps what it learned so far.',
        done: 'Done. Reward went from {first} (first 50 serves) to {last} (last 50). Legal returns during training: {legal}. It is now {sure}% sure about its favourite choice. Next: was 300 enough?',
        noExplore: 'It returned {legal} balls in 300 serves and learned nothing: it always took its first guess, so it never found out that anything else works. Turn exploration on and train again.',
        backToExplore: 'Back to exploration',
        m: { episode: 'Serves', reward: 'Reward (last 20)', contacts: 'Touches', legal: 'Legal returns' },
      },
      7: {
        title: 'Evaluate',
        lead: 'Reward during training can lie. The real test: 20 serves the robot never trained on, before and after learning.',
        note: 'Before = the untrained robot (it always makes the same first guess). After = the brain you trained. Watch the arm choose a height and tilt before each serve.',
        before: 'Before', after: 'After',
        idle: 'Ready.',
        serving: 'Serve {n} of 20 · {who} · arm goes to {height} cm, {tilt} tilt',
        run: 'Run the 20-serve test',
        improved: 'Legal returns went from {b} to {a} on unseen serves. That is real improvement.',
        notImproved: 'Legal returns went from {b} to {a}. It did not improve much — that happens. Go back and train longer, or try the other reward plan.',
      },
    },
    uncertainty: {
      title: 'Should it explore?',
      lead: 'Right now the robot has no idea which of its 15 choices is best — every bar is the same height. Should it sometimes try choices it is unsure about, or always take its current best guess?',
      note: 'The bars show how sure the robot is about each choice for one serve. The orange bar is its favourite.',
      barsLabel: 'How sure the robot is (15 choices)',
      yes: 'Yes — let it try uncertain choices',
      no: 'No — always its best guess',
      yesShort: 'yes', noShort: 'no',
      yesText: 'Exploring. It will sometimes pick a choice it is unsure about — that is how it discovers better ones.',
      noText: 'No exploring. It will always take its current favourite. Let\'s see what that does to learning…',
    },
    enough: {
      title: 'Was 300 enough?',
      lead: 'Engineers do not guess how long to train — they watch the score on unseen serves while training and stop when it stops climbing. Here is that curve.',
      note: 'Green = legal returns on the 20 unseen serves, measured every 20 training serves. The orange mark is 300.',
      curveLabel: 'Legal returns (of 20) vs serves trained',
      summary: 'After 100 serves: {at100}/20. After 300: {at300}/20. Now ({total} serves): {now}/20.',
      more: 'Train 300 more',
      flat: 'After 300 more serves the score went from {at300} to {now} — a gain of {gain}. The curve went flat at about {flatAt} serves; everything after that, including the extra 300, taught nothing new. Engineers stop a safe distance past the flat point — so 300 was plenty here.',
      stillRising: 'After 300 more serves the score went from {at300} to {now} — still climbing by {gain}. So 300 was not quite enough here; the curve tells you, not a rule of thumb.',
    },
    realGame: {
      button: 'Play the real pong game',
      title: 'The real pong game on your computer',
      intro: 'This repo also has the full 3D rally game (MuJoCo physics) where BracketBot\'s whole body — wheels, mast and arm — was trained the same five-step way, just with a bigger brain (PPO) and many more serves:',
      steps: [
        '1 · Task: return a served ball legally, first to 11 points.',
        '2 · Senses: ball position and speed, arm joints, chassis. Controls: 8 corrections to the arm and wheels.',
        '3 · Reward: contact + legal return, penalties for misses (bracket_pong/rally.py).',
        '4 · Train: 300 000 serves of PPO (runs/rally-wheels-match-candidate0).',
        '5 · Evaluate: 67 / 100 held-out human serves returned legally (the baseline managed 16).',
      ],
      outro: 'Run it from the project folder, then play with the mouse (click to swing, Space to serve):',
      commands: [
        '.venv/bin/python -m bracket_pong.play',
        '# train your own (takes a while):',
        '.venv/bin/python -m bracket_pong.train_rally --mobile --output runs/my-wheels --seed 3 --steps 300000',
        '.venv/bin/python -m bracket_pong.evaluate_rally --mobile --model runs/my-wheels/best_model.zip --output artifacts/my-wheels-coverage.json --per-cell 20',
      ],
      warn: 'Needs the Python setup from the README (uv sync --locked).',
    },
    concept: {
      question: 'Which number proves the robot actually returns balls?',
      options: ['The training reward going up', 'Legal returns on the 20 serves it never saw', 'The number of serves it trained on'],
      answer: 1,
      explain: 'Reward is whatever we chose to pay for. Returns on unseen serves are the job itself.',
    },
    badge: 'You set a task, chose senses and controls, designed a reward, decided about exploring, trained, checked how long was enough, and evaluated. Those are the steps of every RL project — including the real BracketBot.',
  },
  vision: {
    title: 'Robot Eyes',
    labels: { red: 'Red', blue: 'Blue', yellow: 'Yellow' },
    steps: {
      1: {
        title: 'Label the photos',
        lead: 'BracketBot\'s head camera took 18 photos of coloured balls. It has no idea what colours are. Tap a photo, then tap the colour you see.',
        note: 'Every label you give becomes one example the robot learns from. Wrong labels teach wrong things.',
        needTwo: 'The robot needs at least 2 examples of every colour before it can learn.',
      },
      2: {
        title: 'Train',
        lead: 'Press Train. The robot fits a tiny brain — 12 numbers — to your 18 labelled examples.',
        note: 'It only looks at the average colour of the middle of each photo. Nothing else.',
        train: 'Train',
        done: 'Trained on {n} examples. It gets {acc}% of them right. But that is on photos it has already seen…',
      },
      3: {
        title: 'Test on new photos',
        lead: 'Here are 12 photos the robot never saw, with different backgrounds and lighting. It got {n} of 12.',
        note: 'Green ✓ = right, red ✗ = wrong. This is the score that matters.',
        total: 'Correct',
      },
      4: {
        title: 'Improve it',
        lead: 'Six tricky photos: dim yellows, purple-ish blues, orange-ish reds. Label them, then train again with 24 examples.',
        note: 'After retraining, the robot is scored on the same 12 test photos so the comparison is fair.',
        retrain: 'Train again (24 examples)',
        done: 'Retrained. Compare the numbers: more examples of the hard cases changed what the robot believes.',
        m: { testBefore: 'Test before', testAfter: 'Test after', hardBefore: 'Tricky before', hardAfter: 'Tricky after' },
      },
      5: {
        title: 'A real object',
        lead: 'Now show the robot something real. Take or choose a photo with one red, blue or yellow thing in the middle.',
        note: 'The robot only reads the middle of the picture (the orange square). Backgrounds and shadows count too.',
        pick: 'Take / choose a photo',
        result: 'The robot says: {label} ({pct}% sure).',
        caveat: 'It has only three answers, so it will call a green apple something. That is not a bug — it is what a 3-class model is.',
        failed: 'Could not read that image. Try another one.',
      },
    },
    concept: {
      question: 'Why test the robot on photos it never trained on?',
      options: ['Because training photos are boring', 'To find out whether it learned the colour, not just those exact photos', 'Because more photos always means a better score'],
      answer: 1,
      explain: 'A model can memorise its examples. Only new examples show whether it learned the idea.',
    },
    badge: 'You collected data, trained a real classifier, tested it honestly, and improved it with harder examples. The real BracketBot\'s camera uses the same steps.',
  },
}
